# coding: utf-8

"""
    Ory Identities API

    This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 

    The version of the OpenAPI document: v1.4.0-alpha.0
    Contact: office@ory.sh
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ory_kratos_client.models.session_device import SessionDevice

class TestSessionDevice(unittest.TestCase):
    """SessionDevice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionDevice:
        """Test SessionDevice
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionDevice`
        """
        model = SessionDevice()
        if include_optional:
            return SessionDevice(
                authentication_methods = [
                    ory_kratos_client.models.authentication_method_identifies_an_authentication_method.AuthenticationMethod identifies an authentication method(
                        aal = 'aal0', 
                        completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        device_trust_based = True, 
                        method = 'link_recovery', 
                        organization = '', 
                        provider = '', )
                    ],
                id = '',
                ip_address = '',
                location = '',
                trusted = True,
                user_agent = ''
            )
        else:
            return SessionDevice(
                id = '',
        )
        """

    def testSessionDevice(self):
        """Test SessionDevice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
