# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Model.SessionDevice do
  @moduledoc """
  Device corresponding to a Session
  """

  @derive Jason.Encoder
  defstruct [
    :authentication_methods,
    :id,
    :ip_address,
    :location,
    :trusted,
    :user_agent
  ]

  @type t :: %__MODULE__{
    :authentication_methods => [Ory.Model.SessionAuthenticationMethod.t] | nil,
    :id => String.t,
    :ip_address => String.t | nil,
    :location => String.t | nil,
    :trusted => boolean() | nil,
    :user_agent => String.t | nil
  }

  alias Ory.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:authentication_methods, :list, Ory.Model.SessionAuthenticationMethod)
  end
end

