# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Model.SessionAuthenticationMethod do
  @moduledoc """
  A singular authenticator used during authentication / login.
  """

  @derive Jason.Encoder
  defstruct [
    :aal,
    :completed_at,
    :device_trust_based,
    :method,
    :organization,
    :provider
  ]

  @type t :: %__MODULE__{
    :aal => Ory.Model.AuthenticatorAssuranceLevel.t | nil,
    :completed_at => DateTime.t | nil,
    :device_trust_based => boolean() | nil,
    :method => String.t | nil,
    :organization => String.t | nil,
    :provider => String.t | nil
  }

  alias Ory.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:aal, :struct, Ory.Model.AuthenticatorAssuranceLevel)
     |> Deserializer.deserialize(:completed_at, :datetime, nil)
  end
end

