/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * The version of the OpenAPI document: v1.4.0-alpha.0
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ory.Kratos.Client.Model;
using Ory.Kratos.Client.Client;
using System.Reflection;

namespace Ory.Kratos.Client.Test.Model
{
    /// <summary>
    ///  Class for testing KratosSessionDevice
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KratosSessionDeviceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for KratosSessionDevice
        //private KratosSessionDevice instance;

        public KratosSessionDeviceTests()
        {
            // TODO uncomment below to create an instance of KratosSessionDevice
            //instance = new KratosSessionDevice();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of KratosSessionDevice
        /// </summary>
        [Fact]
        public void KratosSessionDeviceInstanceTest()
        {
            // TODO uncomment below to test "IsType" KratosSessionDevice
            //Assert.IsType<KratosSessionDevice>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'AuthenticationMethods'
        /// </summary>
        [Fact]
        public void AuthenticationMethodsTest()
        {
            // TODO unit test for the property 'AuthenticationMethods'
        }

        /// <summary>
        /// Test the property 'IpAddress'
        /// </summary>
        [Fact]
        public void IpAddressTest()
        {
            // TODO unit test for the property 'IpAddress'
        }

        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Fact]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }

        /// <summary>
        /// Test the property 'Trusted'
        /// </summary>
        [Fact]
        public void TrustedTest()
        {
            // TODO unit test for the property 'Trusted'
        }

        /// <summary>
        /// Test the property 'UserAgent'
        /// </summary>
        [Fact]
        public void UserAgentTest()
        {
            // TODO unit test for the property 'UserAgent'
        }
    }
}
